### ISSUE TITLE
Requires node >=22.2.0

### ISSUE THREAD

**Issue by vicadam** [aimtbr/use-app-events#1]
Is Node 22 really required? Node 18 & 20 are still in LTS and should be supported.

Used ```yarn --ignore-engines``` to install in a Node 20 project and it works fine. However installing any packages afterwards requires the same flag.

**Comment by aimtbr** [comment]
Hi @vicadam,

You are right, thank you!

After some minor updates and testing, I confirm that from now on, the package will be available not only for Node.js v18, v20, and v22 but also for React v17 and v18

Please update the package and try again, let me know if it works now without `--ignore-engines`

**Comment by vicadam** [comment]
All works great now. Thanks again!
